version: '3.9'

volumes:
  pg_data:
  redis_data:
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local

networks:
  my-network:
    external: true

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - my-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
      - zookeeper_logs:/bitnami/zookeeper/logs

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    networks:
      - my-network
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=gear
      - POSTGRES_DB=tic_tac_toe_db

  gateway:
    build:
      context: ../
      dockerfile: ./docker/backend/gateway/Dockerfile
    container_name: gateway
    networks:
      - my-network
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper

  game-service:
    build:
      context: ../
      dockerfile: ./docker/backend/services/game/Dockerfile
    container_name: game
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - zookeeper
      - postgres

  auth-service:
    build:
      context: ../
      dockerfile: ./docker/backend/services/authorization/Dockerfile
    container_name: auth
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - zookeeper
      - redis
